apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: astronomy-shop
      containers:
        - name: payment
          image: ghcr.io/open-telemetry/demo:2.1.3-payment
          ports:
            - containerPort: 50051
          env:
            - name: PAYMENT_PORT
              value: "50051"
            - name: FLAGD_HOST
              value: flagd
            - name: FLAGD_PORT
              value: "8013"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4317
            - name: OTEL_SERVICE_NAME
              value: payment
          resources:
            limits:
              memory: "120Mi"
