apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting
  template:
    metadata:
      labels:
        app: accounting
    spec:
      serviceAccountName: astronomy-shop
      containers:
        - name: accounting
          image: ghcr.io/open-telemetry/demo:2.1.3-accounting
          env:
            - name: KAFKA_ADDR
              value: kafka:9092
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_SERVICE_NAME
              value: accounting
            - name: DB_CONNECTION_STRING
              value: Host=postgresql;Username=otelu;Password=otelp;Database=otel
          resources:
            limits:
              memory: "120Mi"
