apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  template:
    metadata:
      labels:
        app: quote
    spec:
      serviceAccountName: astronomy-shop
      containers:
        - name: quote
          image: ghcr.io/open-telemetry/demo:2.1.3-quote
          ports:
            - containerPort: 8090
          env:
            - name: QUOTE_PORT
              value: "8090"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_PHP_AUTOLOAD_ENABLED
              value: "true"
            - name: OTEL_PHP_INTERNAL_METRICS_ENABLED
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: quote
          resources:
            limits:
              memory: "40Mi"
