apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      serviceAccountName: astronomy-shop
      containers:
        - name: fraud-detection
          image: ghcr.io/icbannerman/fraud-detection:v1
          env:
            - name: FLAGD_HOST
              value: flagd
            - name: FLAGD_PORT
              value: "8013"
            - name: KAFKA_ADDR
              value: kafka:9092
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_SERVICE_NAME
              value: fraud-detection
          resources:
            limits:
              memory: "300Mi"
